### ISSUE TITLE
[Task] Update the to-do list to a Kanban board

### ISSUE THREAD

**Issue by ksyksy815** [ksyksy815/sagaksagak-client#2]
### ISSUE
- Group:  client
- Type: `feature`
- Detail: Update the current to-do list into a Kanban board with a drag-and-drop function

### TODO
1. [ ] Design a new kanban-board-style to-do list
2. [ ] Apply the new design
3. [ ] Enable the drag-and-drop function of items
