### ISSUE TITLE
[Task] Utilizing usernames in the video chat room

### ISSUE THREAD

**Issue by ksyksy815** [ksyksy815/sagaksagak-client#4]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: Currently, the username is not used in the video chat room. Add several features related to using it to enhance the socializing sentiment among users.

### TODO
1. [ ] When someone's camera is off, show their name instead.
2. [ ] When a new user joins, a notification pops up and disappears after few seconds.
3. [ ] When hover over someone's video, show their name.
