### ISSUE TITLE
[Task] Refactor using useReducer

### ISSUE THREAD

**Issue by ksyksy815** [ksyksy815/sagaksagak-client#7]
### ISSUE
- Group:  `client`
- Type: `refactor`
- Detail: Make a plan to refactor components with not so clean status of states

### TODO
1. [ ] List up target components that need refactoring
2. [ ] Decide whether the listed ones could benefit from being refactored using useReducer
3. [ ] Apply changes
4. [ ] Record the refactored components
