### ISSUE TITLE
[Task] Optimization

### ISSUE THREAD

**Issue by ksyksy815** [ksyksy815/sagaksagak-client#8]
### ISSUE
- Group:  `client`
- Type: `refactor`
- Detail: List up and refactor the components that need optimization

### TODO
1. [ ] List up the components that need optimization
2. [ ] Decide how to make the components more optimized
3. [ ] Refactor components
4. [ ] Record which components have been optimized and how
